name: Deploy Site
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy Site
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: project
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Build Site
        run: |
          npm i

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./project/site
          cname: solar.katsute.dev
          force_orphan: true
          commit_message: ${{ github.event.head_commit.message }}