name: npm CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  npm_ci:
    name: npm CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: project
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          architecture: x64
          node-version: 19

      - name: Build
        run: npm i